### ISSUE TITLE
How we handle lines needs rethinking

### ISSUE THREAD

**Issue by CodyRoberson** [andrewdurkiewicz/CSE360#15]
First take a look at Zach's method for drawing lines. We can agree that his code works.
Lines drawn through the graphics method are applied to JPanelTwo.

There is a big catch, the code only works until the program has to call repaint. When repaint is called those graphics are still deleted. 

This is where my method DrawPanelTwo.updatePanel calls drawPanelLines. The problem here lies with the fact that each line is redrawn **as its own DrawArrow object.** No longer are the lines drawn onto the panel but rather onto a large stack of DrawArrows(which extend JLabel). This wouldn't be so bad, except that setBounds effectively makes the label the same size as DrawPanelTwo. This means that any future listeners used to select and delete the lines will likely only be able to click the Lines at one layer at a time. This will create unexpected results.

I don't a good fix, because simply trying to redraw lines back onto panel2 doesn't work for some reason. I suppose the graphics could be drawn on a layer within the panel but I'm having programmers block. I would appreciate you guys taking a look.

_**The next problem is that I don't think the graphics lines are objects and therefore I don't now if we can even add event listeners to them.**_

**Comment by CodyRoberson** [comment]
I am currently working in branch: Alveron.

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson im 100% sure we need to use threading

**Comment by CodyRoberson** [comment]
how do you mean?

**Comment by andrewdurkiewicz** [comment]
You literally cant have two mouselisteners running at the same time, they superimpose. So, you connect one to one thread, another to another, and silence one after reading from the other.

**Comment by andrewdurkiewicz** [comment]
maybe we give each icon object a center and tell the line, when clicking in two objects, your ends will be located at those two objects centers

**Comment by andrewdurkiewicz** [comment]
> There is a big catch, the code only works until the program has to call repaint. When repaint is called those graphics are still deleted.

No they are not, i've tested this before. Cody stores them in DraggableIcon type array
so they maintain the same properties

**Comment by andrewdurkiewicz** [comment]
@zcarnago @CodyRoberson don't worry, I have this handled. You will see a ton of code changes coming in the coming day. It wont be recognizable. I have it all planned out. I can explain more in detail if you wish.

**Comment by CodyRoberson** [comment]
cool, but how do we differentiate between which DrawArrow is being clicked?
Each draw arrow is the same size object but transparent.
Picture looking straight down at a stack of paper. How can you interact with the paper below it without interacting with the top sheet?  How can a user select a drawing that is in the middle of the stack when the other papers are in the way?

**Comment by andrewdurkiewicz** [comment]
Sorry for so many replies. Basically here is the summary. I have confirmed that by giving the icons a mouseListener, the icons maintain their object type. I know it 100%. The issue is that we cant click an object and find where it is relative to panel2. We need to use threading. MouseListener for panel2 in one thread and MouseListener for Icon type in another. Then, we say:
`if(e.getSouce().instanceof(icon){
    then->silence thread1 and  trigger thread 2`
I think this can be done with something called temp.dispatchEvent(e);
which triggers the event

**I need to stress. Im taking lead, but in no way is this my job only. So please don't expect me to do this myself**

**Comment by CodyRoberson** [comment]
im not talking about the icons, I'm talking about each and every arrow that gets drawn.

**Comment by andrewdurkiewicz** [comment]
What about it?

**Comment by andrewdurkiewicz** [comment]
I think an easy solution is: make an arrow type which gets its location (not from the array) but now from the icon type. We can add a private x, y for each icon and a getX and getY method for it. So when painting, it just needs to call that for each one.

**Comment by andrewdurkiewicz** [comment]
This is what I saw: 
https://docs.oracle.com/javase/7/docs/api/java/awt/Component.html#getIgnoreRepaint()
![image](https://user-images.githubusercontent.com/13666544/41198027-804d1418-6c23-11e8-97d4-962a8c4a85e5.png)

**Comment by CodyRoberson** [comment]
ok cool, lets say we stick with 2d graphics. In otherwords with lines painted onto some component. How do we interact with said lines if they are not objects?

**Comment by andrewdurkiewicz** [comment]
Here is what I say we do. We make the lines a subclass of the icons. Then, when two are connected, they kinda point to each other. that way we can constantly find their position if they need to move

**Comment by andrewdurkiewicz** [comment]
Cody, Do you think this will work for my JTextArea? I want to save it as a png, then repaint it wherever the user clicks
Not that it wont look nice, but it satisfies the UC. I will make it a png, then use your draggable icon with it.

**Comment by andrewdurkiewicz** [comment]
Found this code and I want to use it to make the png, then make a new Draggable class from it. 
`        btnPrint.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                BufferedImage img = new BufferedImage(text.getWidth(), text.getHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics2D g2d = img.createGraphics();
                text.printAll(g2d);
                g2d.dispose();

                try {
                    ImageIO.write(img, "png", new File("StringToGraphics.png"));
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

            }
        });`

**Comment by CodyRoberson** [comment]
I think you have two ways of going about it.
A)The way you're describing
B) change DraggableIcons to be little jpanels instead of jlabels with their icon as a background and have a text box inside them.

**Comment by andrewdurkiewicz** [comment]
I can scale it later on as well if needed

**Comment by CodyRoberson** [comment]
true true ^_^

**Comment by andrewdurkiewicz** [comment]
I am leaving this issue open till closed. Please fill UC diagram out. It took 5 min and it will allow us to spread work around as needed. 
@CodyRoberson @zcarnago @aztcole

**Comment by CodyRoberson** [comment]
SO, there are now 4 SRS documents....which one?

**Comment by andrewdurkiewicz** [comment]
Regarding that, @zcarnago had an issue where the document literally disappeared and I spent 3 hours trying to get it back. I think it would be best to never use onedrive again. **Use new.docx** I am leaving the others as backups.

**Comment by andrewdurkiewicz** [comment]
So....I got it. The lines are a bit off by a constant amount. can someone see if they know why? Lines only go when you click two objects in sequence. Its a bit buggy but that part works @CodyRoberson @zcarnago @aztcole
