### ISSUE TITLE
Requesting advice for part e

### ISSUE THREAD

**Issue by andrewdurkiewicz** [andrewdurkiewicz/CSE360#24]
> e. You should add a JTextArea to your GUI. In real time, every time that you draw
something, the JTextArea will update. The JTextArea will show the source code
equivalent to your draw. For instance,
Adding a new square to the working area will show in the JTexArea
public class Icon1 {
}
Adding a second square and then a circle will show
public class Icon1 {
}
public class Icon2 {
}
public interface Icon3 {
}
As you notice, squares will represent classes and circles will represent interfaces. You
can name them with a consecutive number or you can implement a functionality in which
you ask the user for a name every time you drag an icon in the working area.
When you connect two icons the JTextArea will update the code. For instance,
connecting Icon1 and Icon2 with and aggregation line and Icon2 with Icon3 using
inheritance will generate in real-time the following
public class Icon1 {
 Icon2 icon2; // notice upper case for class and lower case for object
}
public class Icon2 implements Icon3{
}
public interface Icon3 {
}

This is what I want to work on. But @CodyRoberson , I worry that since we effectively turn these objects into DraggableObjects, I cant possibly differentiate between shapes. He says we should have a shape() class, or we can have two: circle() and square(). Can we make that happen so I can find the class and print on the JTextArea from there?

**Comment by andrewdurkiewicz** [comment]
The reason I think that it wont work is that we are repainting DraggableObjects. Not a circle or square object.

**Comment by CodyRoberson** [comment]
The first solution I can think of would be to create individual shape classes that extend DraggableIcon. We could just split draggable icon into several unique icon children.....or wrap them, and that would be it. I mean, there are a lot of possibilities here.
