### ISSUE TITLE
Not sure how to implement the Draw() method

### ISSUE THREAD

**Issue by andrewdurkiewicz** [andrewdurkiewicz/CSE360#25]
From B in the assignment: 

> You should have a class Icon. Optionally you could have also a class IconSquare or
IconCircle. **This class should have the method that draw the icon on the screen. Please
name this method draw()**. You can add as many parameters as you need. You should
have an object icon for each line draw on the screen

The way I have it now, iconCircle and iconSquare extend DraggableIcon. I have no clue how Draw would be used in this case. Any Ideas?

**Comment by CodyRoberson** [comment]
**If he means draw as in create the graphic**
I don't know. I'll think on this.
**If  he means a method to simply add the icon to DrawPanelTwo**,
I think our best option is to optimize and re implement the code in:
`public void drop(DropTargetDropEvent dtde)`
into the respective classes draw method. Then, it can notify it's observers.

**Comment by andrewdurkiewicz** [comment]
@cody i have to go to work I get off at 11 and if i dont work tomorrow ill pull an all nighter till i finish
Can you or @aztcole basically explain how the observer and observable work? I've been looking them up all over the web and I don't understand. But if you give me dumbed down version I may be able to implement it correctly. Right now my issue is just not understanding how it works

**Comment by CodyRoberson** [comment]
ok
i made an example

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson @aztcole i got it i think can you guys tell me if i did the same thing again or did it right

**Comment by andrewdurkiewicz** [comment]
merging
 now

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson look at my branch i have to go but for some reason when i try to loop through your array "to reprint it" it prints three of the same type. I don't think its me. I think its actually like this in memory. in DataHandler to be exact
![image](https://user-images.githubusercontent.com/13666544/42120190-e274c994-7bcb-11e8-83d9-3bf005e6c6e9.png)

then after adding another:
![image](https://user-images.githubusercontent.com/13666544/42120194-f06f1518-7bcb-11e8-942e-5dc2559267a6.png)

**Comment by andrewdurkiewicz** [comment]
Maybe I am not looping correctly

**Comment by CodyRoberson** [comment]
okay. cool, thanks for your hard work. Am taking a look rn.

**Comment by andrewdurkiewicz** [comment]
havent pushed yet. its on my latest branch too late to delete other. will do tonight. pushing then going.

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson update?

**Comment by CodyRoberson** [comment]
mmm just planning the design, also I have no idea why the string type stays the same
sorry. I'm just going to re-design the DraggableIcon structure and related sub classes.

**Comment by CodyRoberson** [comment]
did you get it working?

**Comment by andrewdurkiewicz** [comment]
just got off work. working on it now
i figured out how to use eclipse debugger. I think there is a point where we make a comparison (i.e if(x == y);, where we are actually putting (i.e. if(x=y);) effectively redefining x as y. i had this issue with my last homework in 310

**Comment by andrewdurkiewicz** [comment]
but its not in my code. Which means something is wrong with DataHandler. When looking at the heap, it seeps that it is literally changing the value of it. Though, let me test a bit more to find the exact location

**Comment by CodyRoberson** [comment]
DataHandler can't possible be at fault though, when it comes to holding onto the icons and arrows, it doesn't have any conditionals, just getters and setters.

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson Can you explain this in line 88 in DataHandler 
`IconRecord =temp.get(0);
ArrowRecord = temp.get(1);`

is get a built in function for ArrayList or is a function you made?

**Comment by andrewdurkiewicz** [comment]
I think you are right. I maybe changed something and broke it. But, its redefining it on repaint.

**Comment by CodyRoberson** [comment]
so when you make an object output stream, you can only use one object.
Therefore the root of the tree is needed so to speak. So both array lists are packed into another single array list.

When the object is imported, it becomes an array list of those array lists

temp.get(0) is just the first list
temp.get(1) is the second

**Comment by CodyRoberson** [comment]
like putting files into a zip folder

**Comment by andrewdurkiewicz** [comment]
but, you are redefining it there

**Comment by CodyRoberson** [comment]
how do you mean? these functions are isolated from the rest of the program since they are called to load and save the diagram ONLY from the file menu.

**Comment by andrewdurkiewicz** [comment]
I'm dumb. Please ignore. Give me a bit. I'll find it. I think, you may be redefining then adding.

**Comment by andrewdurkiewicz** [comment]
Yeah. Very good job on this btw

**Comment by CodyRoberson** [comment]
thx, also only load does redefining, and that wipes out the whole thing. I don't see any connection to the problem of types tho.

**Comment by andrewdurkiewicz** [comment]
No, I agree.

**Comment by andrewdurkiewicz** [comment]
im going to make a void to print of whats in the array before and after. See if its in this

**Comment by CodyRoberson** [comment]
what branch are you working on rn?

**Comment by andrewdurkiewicz** [comment]
[https://github.com/andrewdurkiewicz/CSE360/tree/observerimplement](link)

**Comment by andrewdurkiewicz** [comment]
Pushing now
Only cleaned up the whitespace

**Comment by andrewdurkiewicz** [comment]
OMG observable is an interface. Its just called subject

**Comment by CodyRoberson** [comment]
just typing up the best explanation that i can

**Comment by CodyRoberson** [comment]
The observer basically presides over the observable objects that are added to it.
ex:
`addObserver(/*observer object here*/)`

When an observable object that belongs to an observer changes in some way that we want to let everyone know, we call these methods:
 `
setChanged(); 
notifyObservers();
`
the observer then runs it's update method where `Observable o` is a reference to the object that notified the observer.  From there, the update method can do whatever with that.

**Comment by andrewdurkiewicz** [comment]
Does what i'm doing make any sense to you here? Does it sound like a good idea?
![image](https://user-images.githubusercontent.com/13666544/42123180-4c79d79a-7c02-11e8-8195-4c26d44d67dc.png)

**Comment by andrewdurkiewicz** [comment]
I know the errors exist but, this would work. I'm sure of it

**Comment by CodyRoberson** [comment]
wait, why are you trying to do what i"m assigned?

**Comment by CodyRoberson** [comment]
nice

**Comment by CodyRoberson** [comment]
@andrewdurkiewicz 

I noticed that you added your node to dragGestureRecognized, make sure to verify that the n object doesn't get deleted when this method call ends, because it might invalidate the observable ovject
        public void dragGestureRecognized(DragGestureEvent dge) {
+               System.out.println("here");
                Transferable txfr = new StringSelection(imgSource);
                dSource.startDrag(dge, DragSource.DefaultCopyDrop, txfr, this);
+               Nodes n = new Nodes();
+               nodeObserver o = new nodeObserver();
+               n.addObserver(o);
+               n.addSingle(new Nodes(this));
+
+               
        }

**Comment by andrewdurkiewicz** [comment]
wait your up?
btw i got it all working..

**Comment by andrewdurkiewicz** [comment]
everything

**Comment by andrewdurkiewicz** [comment]
check my push

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson 
not gonna lie, kinda want to merge

**Comment by CodyRoberson** [comment]
nice work my dude. I will likely be able to implement the lines with this

**Comment by andrewdurkiewicz** [comment]
I stayed up all night and...i cant get it working. I cant do comparisons since it repaints
so arrows are almost impossible. brainstorm for me and see if you have ideas.

**Comment by CodyRoberson** [comment]
what class?

**Comment by andrewdurkiewicz** [comment]
nodeobserver does all the work with texteditor

**Comment by andrewdurkiewicz** [comment]
if you cant understand ill explain on discord and leave i just need a break

**Comment by CodyRoberson** [comment]
okay link?

**Comment by CodyRoberson** [comment]
sorry lost it :(

**Comment by andrewdurkiewicz** [comment]
1s let me fix something then push

**Comment by andrewdurkiewicz** [comment]
k, lots of it wont make sense ill do my best

**Comment by andrewdurkiewicz** [comment]
https://discord.gg/JVUYTY

**Comment by andrewdurkiewicz** [comment]
@aztcole @zcarnago @CodyRoberson Can you guys quickly remind me what each type of thing (aggregation, inherit, etc) looks like in code form? I think i got it

**Comment by CodyRoberson** [comment]
okay, let me stop you there. Please do not implement those options, rather, present your ideas to us  instead of doing the whole project yourself. That wouldn't be fair.

see: 
https://docs.google.com/document/d/15uVignOJrNHWOI0G6WuXo_83adKodJoEj5nE0ZDsQlI/edit
(you must be logged into your asu account)

For the documentation on each members responsibilities.

**Comment by andrewdurkiewicz** [comment]
well im very close . do you want to take over? i cant seem to figure out why my icons increment by 1 when  making an arrow

**Comment by CodyRoberson** [comment]
Sure, what exactly works and doesn't work.

**Comment by andrewdurkiewicz** [comment]
Ill push and youll see my issues. it would work if it didnt increment the counter on clicking of the first icon when making a line. Hopefully this makes sense to you. When i have two icons, I click one and then the other, but for some reason it prints correct but the Icon# goes up by one

**Comment by andrewdurkiewicz** [comment]
Really good example of what I mean:
Before:

![image](https://user-images.githubusercontent.com/13666544/42128626-9fc4cb82-7c64-11e8-9279-bd9aee4f85f1.png)


After Association (for all lines)
![image](https://user-images.githubusercontent.com/13666544/42128630-b780dff4-7c64-11e8-826c-a369be8a0922.png)

**Comment by andrewdurkiewicz** [comment]
pushing

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson I got like an 89 on the last project. I figured i wasn't doing enough or something. thats why i'm doing this. Plus I hate this code so much I cant stop trying.

**Comment by andrewdurkiewicz** [comment]
also, i know all those subtypes like association are wrong, i was simply testing it

**Comment by andrewdurkiewicz** [comment]
But, what you will notice is that the values seem to increment up on the first click. I got around our earlier problem by actually giving draggableIcon a string type that holds that value. fyi

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson I FIXED IT

**Comment by andrewdurkiewicz** [comment]
sorry couldnt help myself. I love programming:P

**Comment by zcarnago** [comment]
Let me know when you push so we can check it out!

**Comment by andrewdurkiewicz** [comment]
by fixed I mean a bug in my code. now I can finish

**Comment by andrewdurkiewicz** [comment]
but you can pull that branch whenever

**Comment by andrewdurkiewicz** [comment]
nvmd i suck

**Comment by zcarnago** [comment]
Not at all man. You guys are wizards compared to me. Im trying to keep up with all the stuff you guys added last night and continue to add. Im kinda a bump on the log and I apologize for that. Please keep throwing ideas and stuff here and ill try my best to help.

**Comment by andrewdurkiewicz** [comment]
Serious Question, am I allowing "public interface Icon1 implements Icon2" Even though its bad?

**Comment by zcarnago** [comment]
Are you trying to mirror the expected output that’s provided on the project instructions? It shows exactly how it should work.
