### ISSUE TITLE
Okay team here is the update

### ISSUE THREAD

**Issue by andrewdurkiewicz** [andrewdurkiewicz/CSE360#32]
I got the text working, deletion working, and most of the stuff working with bugs. Cody is going to do his best to fix those bugs . Those incude, the text doesn't reflect when you delete via alt+ click.

@zcarnago I need you to make a jlabel or something to basically tell the people they can delete via alt + click. When cody is done can you clean up the code. Like, get rid of white spaces and such? 

To both of you: i'm not going to bed, i'm just brain dead. I'm here on discord if you need me.

**Comment by zcarnago** [comment]
For sure. I can do that.

**Comment by CodyRoberson** [comment]
sounds good
